### ISSUE TITLE
Update Actions Secrets

### ISSUE THREAD

**Issue by konturn** [tlc-pack/ci#4]
The DISCORD_WEBHOOK_URL secret needs to be updated for the nightly build notifications, and a new secret with name DOCKERHUB_TOKEN_TLCPACKSTAGING needs to be created to allow the nightly builds to push to the tlcpackstaging dockerhub account.

**Comment by areusch** [comment]
i see DISCORD_WEBHOOK_URL already there, added DOCKERHUB_TOKEN_TLCPACKSTAGING

**Comment by areusch** [comment]
also updated DISCORD_WEBHOOK_URL, which was previously set to staging.
